# Generated by Django 6.0.3 on 2026-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('building', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=50)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('sample_count', models.IntegerField()),
                ('co2_min', models.IntegerField()),
                ('co2_max', models.IntegerField()),
                ('co2_avg', models.FloatField()),
                ('room_score', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='dashboard_s_session_9ad6a5_idx'), models.Index(fields=['building', 'room_number'], name='dashboard_s_buildin_e4aa73_idx'), models.Index(fields=['building', 'room_number', 'mode'], name='dashboard_s_buildin_74f15c_idx')],
            },
        ),
    ]
