# Generated by Django 6.0.3 on 2026-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=10)),
                ('session_ids', models.JSONField(default=list)),
                ('sample_count', models.IntegerField()),
                ('co2_min', models.IntegerField()),
                ('co2_max', models.IntegerField()),
                ('co2_avg', models.FloatField()),
                ('room_score', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='sessionstats',
            name='dashboard_s_session_9ad6a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionstats',
            name='dashboard_s_buildin_e4aa73_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionstats',
            name='dashboard_s_buildin_74f15c_idx',
        ),
        migrations.DeleteModel(
            name='SessionStats',
        ),
        migrations.AddIndex(
            model_name='roomstats',
            index=models.Index(fields=['building', 'room_number'], name='dashboard_r_buildin_9ae8ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomstats',
            unique_together={('building', 'room_number')},
        ),
    ]
