# Generated by Django 6.0.3 on 2026-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=10)),
                ('unix_timestamp', models.BigIntegerField()),
                ('co2_ppm', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='JSONLog',
        ),
    ]
