# Generated by Django 6.0.3 on 2026-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_co2reading_delete_jsonlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='co2reading',
            index=models.Index(fields=['building'], name='api_co2read_buildin_1fbbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='co2reading',
            index=models.Index(fields=['building', 'room_number'], name='api_co2read_buildin_7f3a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='co2reading',
            index=models.Index(fields=['building', 'room_number', 'mode'], name='api_co2read_buildin_670144_idx'),
        ),
        migrations.AddIndex(
            model_name='co2reading',
            index=models.Index(fields=['building', 'room_number', 'unix_timestamp'], name='api_co2read_buildin_e680c9_idx'),
        ),
    ]
