# Generated by Django 6.0.3 on 2026-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_co2reading_api_co2read_buildin_1fbbf0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2reading',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
